miloide/MiloServer

public/scripts/custom/blocks.js
Fixes https://github.com/4and4/MiloServer/issues/23
=> FIX: Zip Lists Issue#23

public/scripts/custom/functions.js
=> Show legend on single trace

public/datasets/california_housing.js, public/datasets/datasets.js, public/datasets/iris.js, public/scripts/custom/helpers.js
=> FIX: Issue #36

.github/PULL_REQUEST_TEMPLATE.md, README.md
Instructions for installing and running MiloServer
=> Readme patch

app.js, database.js, package-lock.json, package.json
=> FIX: db connection error

src/blocks.js, src/codegen.js, src/statistics/cdf.js, src/statistics/pmf.js, views/toolbox.html, webpack.config.js
Resolves function plots
Adds code gen for block-x
Did not work as expected previosuly
Refactored naming conventions
=> FIX : function plot, refac : variables

src/strings.js
Updates block colors to more appealing hues.
=> patch: updated block colors

src/strings.js
=> FIX: block colors

app.js
=> FIX: db connection

app.js
=> fix: eslint errors

.babelrc, package-lock.json, package.json, src/functions.js, webpack.config-test.js, webpack.config.js, webpack.dev.config.js
Changes:
* Added babel loader
* Fixed minor bugs
=> FIX: es6 bugs in firefox

config/auth.js, models/user.js, routes/users.js, views/ide.pug, views/register.pug
* Adds option while registering to allow faculty to sign-up
* Display's user's role in the menubar
* Defaults Google Sign-In to Student account 
* Support faculty to login with Google - Add an option to view user profile when dashboard is compelete - with option to upgrade to faculty account
=> Adds User role field

src/milo.js, views/ide.pug
Issue with XML tab being cleared on moving back to workspace
=> FIX: XML to Blocks

.eslintrc.json, public/ng/dashboard.js, routes/editor.js, routes/store.js, routes/users.js, src/milo.js, src/project.js, src/storage.js, views/dashboard.pug, views/ide.pug
* Retrieve project list based on category (own, shared, trashed)
* Implement action to rename projects
* Implement action to trash project
* Implement action to restore project
* Implement UI to view collaborators
* Implement action to edit and remove collaborators
* Implement search by project name
* Implement clone project functionality
=> FEA: Project Dashboard

app.js, public/ng/dashboard.js, src/datasets.js
* Fixes bug with connect-flash being removed
=> Patch flash fix

app.js
* Fixes bug with missing import
=> Fix: flash bug

src/functions.js, src/milo.js, src/sandbox.js, views/toolbox.html
Fixes issues due to left over code from deeplearn.js
=> FIX: TF Blocks

views/head.pug, views/layout.pug
Adds Google Analytics scripts.
=> Added google analytics

src/mobilenet.js, views/toolbox.html
Fixes #112 
* Load mobilenet model only once
* Wait for images to load before trying to predict
=> FIX: Mobilenet Loading

routes/store.js
Fixes issue with public projects
=> FIX: Public project loading

src/functions.js
=> FIX: Clear KMeans output

src/milo.js, src/sidebar.js, src/storage.js, views/ide.pug
Fixes bug with auto saving when creating new projects.
=> FIX: Autosave on new project

src/datasets.js, src/storage.js
=> Fix dataset save

src/storage.js
=> FIX: Dataset block saving

package.json, src/helpers.js, tests/helpers.spec.js, webpack.config-test.js
=> WIP: testing
